# Zerqavon XMRig custom integration for HiveOS
# Keep this name compatible with existing Zerqavon Flight Sheets.
CUSTOM_NAME=zerqavon-miner
CUSTOM_VERSION=6.26.0-zqv2
CUSTOM_CONFIG_FILENAME=/hive/miners/custom/zerqavon-miner/zerqavon.conf
CUSTOM_LOG_BASEDIR=/var/log/miner/custom/zerqavon-miner
CUSTOM_LOG_BASENAME=/var/log/miner/custom/zerqavon-miner/zerqavon-miner
LIBCURL3_COMPAT=0
