# Zerqavon XMRig custom integration for HiveOS
CUSTOM_NAME=xmrig-zqv
CUSTOM_VERSION=6.26.0-zqv2
CUSTOM_CONFIG_FILENAME=/hive/miners/custom/xmrig-zqv/zerqavon.conf
CUSTOM_LOG_BASENAME=/var/log/miner/custom/xmrig-zqv
LIBCURL3_COMPAT=0
